apiVersion: apps/1 
kind: Deployment 
metadata: 
  name: forntend-deployment
  namespace: production
  labels:   
    app: frontend 
specs: 
  replicas: 3
  selectors:
    matchLabels:  
      app: frontend
  template:
    metadata:
      labels: 
        app: frontend 
    spec: 
      containers: 
        - name: frontend-pod
          image: httpd 
          ports: 
            - containerPort: 80
      imagePullSecrets:
        - name: docker-secrets
---
apiVersion: v1 
kind: Service 
metadata: 
  name: frontend-svc
  labels: 
    app: frontend 
specs:
  type: ApplicationLoadBalancer
  selector:
    app: frontend 
  ports:
    - targetport: 80
      port: 80
      protocol: TCP